### ISSUE TITLE
Mathieu functions

### ISSUE THREAD

**Issue by kalvotom** [JuliaMath/GSL.jl#54] opened 2016-05-31 12:41 UTC
Hi!

I am having trouble computing values of Mathieu functions using the GSL.jl wrapper. For example:

``` sh
julia> using GSL

julia> sf_mathieu_ce(1, 0., 1.0)
GSL.gsl_sf_result(5.0e-324,0.0)

julia> sf_mathieu_ce(1, 0., 2.0)
GSL.gsl_sf_result(1.0e-323,0.0)

julia> sf_mathieu_ce(1, 0., 3.0)
GSL.gsl_sf_result(1.0e-323,0.0)
```

If I am not mistaken, the value of $ce_1(0, x)$ should be equal to that of $\cos(x)$ (maybe up to some normalization).

Other functions return "zero" too:

``` sh
julia> sf_mathieu_se(4, 10., 30.0)
GSL.gsl_sf_result(6.93008513984393e-310,6.9296557058916e-310)
```

Am I missing something? I will be happy to provide more info if needed.

**Comment by jiahao** [comment] 2016-05-31 13:37
I think you have the arguments in the wrong order.

[The manual states](https://www.gnu.org/software/gsl/manual/html_node/Angular-Mathieu-Functions.html#Angular-Mathieu-Functions):

>Function: int gsl_sf_mathieu_ce (int n, double q, double x)
>Function: int gsl_sf_mathieu_ce_e (int n, double q, double x, gsl_sf_result * result)
>Function: int gsl_sf_mathieu_se (int n, double q, double x)
>Function: int gsl_sf_mathieu_se_e (int n, double q, double x, gsl_sf_result * result)
>
>These routines compute the angular Mathieu functions ce_n(q,x) and se_n(q,x), respectively.

The NIST [DLMF](http://dlmf.nist.gov/28.6#ii) gives

- ce_0(z,q=0) = sqrt(1/2)
- ce_1(z,q=0) = cos(z)
- ce_2(z, q=0) = cost(2z)

and it looks like GSL gives the correct values for some special values of z:

```jl
julia> sf_mathieu_ce(0, 0., 0.)
GSL.gsl_sf_result(0.7071067811865475,4.440892098500626e-16)

julia> sf_mathieu_ce(1, 0., 0.)
GSL.gsl_sf_result(1.0,4.440892098500626e-16)

julia> sf_mathieu_ce(2, 0., 0.)
GSL.gsl_sf_result(1.0,4.440892098500626e-16)

julia> sf_mathieu_ce(1, 0., π/4)
GSL.gsl_sf_result(0.7071067811865476,4.440892098500626e-16)

julia> sf_mathieu_ce(2, 0., π/8)
GSL.gsl_sf_result(0.7071067811865476,4.440892098500626e-16)
```

**Comment by kalvotom** [comment] 2016-05-31 13:59
Yes, I am aware of the order of arguments ($q$ is the second one in GSL.jl).

Anyway, I am not able to reproduce your results (which I perfectly agree with):

```sh
julia> using GSL

julia> sf_mathieu_ce(0, 0., 0.)
GSL.gsl_sf_result(6.9483068073792e-310,6.94788041570527e-310)

julia> sf_mathieu_ce(1, 0., 0.)
GSL.gsl_sf_result(5.0e-324,6.94787737493596e-310)
```

So, there is something wrong with my version of Julia/GSL.jl??

**Comment by jiahao** [comment] 2016-05-31 14:35
Sorry, I misread your original post.

That seems like a genuine problem with the GSL wrapper or the library then.

What does `versioninfo()` in Julia say? and what version of GSL are you using, and how did you install it?

**Comment by kalvotom** [comment] 2016-05-31 16:00
`versioninfo()` prints:

```sh
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.3
```

I used Julia package manager to install GSL.jl, i.e. I run the command `Pkg.add("GSL")`. On my system I have GSL version 2.1:

```sh
$ pacman -Ss gsl
extra/gsl 2.1-2 [installed]
    The GNU Scientific Library (GSL) is a modern numerical library for C and C++
    programmers
```

**Comment by jiahao** [comment] 2016-06-01 20:22
Oh, I see. I don't actually support GSL 2.1; when I last actively worked on this package GSL was on 1.16.

Would it be possible for you to try 1.16 and see if the problem is still there? I wonder if the API changed between 1.x and 2.x for the Mathieu functions.

**Comment by kalvotom** [comment] 2016-06-01 21:35
You are right! I am sorry I did not notice your mention of version 1.16 in the README. My mistake.

I downgraded my GSL to 1.16.

```sh
$ pacman -Ss gsl | grep install
extra/gsl 2.1-2 [installed: 1.16-1]
```

and indeed I get correct results now:

```sh
julia> using GSL
INFO: Recompiling stale cache file /home/kalvin/.julia/lib/v0.4/GSL.ji for module GSL.

julia> sf_mathieu_ce(0, 0., 0.)
GSL.gsl_sf_result(0.7071067811865475,4.440892098500626e-16)

julia> sf_mathieu_ce(1, 0., 0.)
GSL.gsl_sf_result(1.0,4.440892098500626e-16)
```

So there is some problem with the 2.1 version of GSL.

I tried to run `Pkg.test("GSL")` with 1.16 installed and all tests passed. With 2.1 installed some tests fail:

```sh
julia> Pkg.test("GSL")
INFO: Testing GSL
INFO: Recompiling stale cache file /home/kalvin/.julia/lib/v0.4/GSL.ji for module GSL.
(...lots of output...)
ERROR: LoadError: LoadError: test error in expression: sf_legendre_Plm_array(lmax,m,x) == [2.25,5.625,4.21875,-4.921875]
ccall: could not find function gsl_sf_legendre_Plm_array in library /usr/lib/libgsl.so
 in sf_legendre_Plm_array at /home/kalvin/.julia/v0.4/GSL/src/../src/_7_24_2_Associated_Legendre_Polynomials_and_Spherical_Harmonics.jl:47
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in anonymous at /home/kalvin/.julia/v0.4/GSL/test/7_24_2_Associated_Legendre_Polynomials_and_Spherical_Harmonics.jl:9
 in sf_legendre_Plm_array at /home/kalvin/.julia/v0.4/GSL/src/../src/_7_24_2_Associated_Legendre_Polynomials_and_Spherical_Harmonics.jl:47
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in anonymous at /home/kalvin/.julia/v0.4/GSL/test/7_24_2_Associated_Legendre_Polynomials_and_Spherical_Harmonics.jl:9
while loading /home/kalvin/.julia/v0.4/GSL/test/7_24_2_Associated_Legendre_Polynomials_and_Spherical_Harmonics.jl, in expression starting on line 4
while loading /home/kalvin/.julia/v0.4/GSL/test/runtests.jl, in expression starting on line 12
=================================[ ERROR: GSL ]=================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/kalvin/.julia/v0.4/GSL/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: GSL had test errors
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

It looks like 2.1 breaks more things then just Mathieu functions...

I will stick to 1.16.

**Comment by ludvigak** [comment] 2018-11-14 16:22
This should be fixed now, since GSL.jl provides its on binary of the GSL library (version 2.5).

**Closed by ludvigak** 2018-11-14 16:22 UTC
Labels: gsl-2.0
